# Gradle 运行参数
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft 环境配置
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

# 映射通道：official（官方）或 parchment（社区增强）
mapping_channel=official
mapping_version=1.20.1

# 模组基本信息
mod_id=void_things
mod_name=Void Things
mod_license=GNU LGPLv3
mod_version=0.0.2
mod_group_id=nothing.xiaofan_delta.void_things
mod_authors=Xiaofan-Delta
mod_description=Void Things Mod - Bring 'Nothing' to Your Minecraft

# JEI 集成
jei_version=15.49.0.188

# Nebula Libs
nebula_lib_version=2.5.2